In [58]:
from scipy.fftpack import fft
import skimage.io as io
import os as os 
import numpy as np
import skimage.filters as filt
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

# Loading Images for FFT

In [61]:
region_features=[]
classes=[]
test_region = []
train_region = []
train_classes_region = []
test_classes_region =[]

minimum=0.0
maximum=0.0
for root, dirs, files in os.walk('Data/Combined_Data'):
    for filename in files:
        cropped_image =  io.imread(root+'/'+filename)
        cropped_image = filt.unsharp_mask(cropped_image, radius=1, amount=4)
        image_class = root.replace("\\","/").split('/')[2]
        print("Processed Image: "+str(filename)+" Class: "+str(image_class))
        fourier = fft(cropped_image).flatten()
        fourier = np.true_divide(fourier, np.count_nonzero(fourier))
        hist,bins = np.histogram(fourier,bins=5)
        print(hist)
        region_features.append(hist)
        classes.append(int(image_class))

train_region,test_region,train_classes_region,test_classes_region=train_test_split(region_features, classes, test_size=0.33)

Processed Image: G0166380.JPG Class: 1
[1242  111  144  120   99]
Processed Image: G0166381.JPG Class: 1
[1040  112  116   90   82]
Processed Image: G0166382.JPG Class: 1
[1738  120  163  188  131]
Processed Image: G0166383.JPG Class: 1
[1154   96  128  105   92]
Processed Image: G0166384.JPG Class: 1
[1094   94  118  109   97]
Processed Image: G0296469.JPG Class: 1
[4095  477  472  466  262]
Processed Image: G0296472.JPG Class: 1
[4463  457  591  553  263]
Processed Image: G0296473.JPG Class: 1
[5462  641  826  676  261]
Processed Image: G0296474.JPG Class: 1
[1656  164  248  169  115]
Processed Image: G0296476.JPG Class: 1
[1726  166  265  187  104]
Processed Image: G0296477.JPG Class: 1
[1485  125  236  167   87]
Processed Image: G0296478.JPG Class: 1
[1182   89  192  122   71]
Processed Image: G0296481.JPG Class: 1
[1122  101  174  121   66]
Processed Image: G0306486.JPG Class: 1
[1462  128  136  179  111]
Processed Image: G0306487.JPG Class: 1
[2384  258  305  225  176]
Processed 

D:\Anaconda_Installed\lib\site-packages\numpy\lib\function_base.py:786: ComplexWarning: Casting complex values to real discards the imaginary part
  tmp_a_data = tmp_a.astype(float)
D:\Anaconda_Installed\lib\site-packages\numpy\lib\function_base.py:792: ComplexWarning: Casting complex values to real discards the imaginary part
  indices = tmp_a.astype(np.intp)


Processed Image: IMG_4444.JPG Class: 10
[1376707  203747  276656  296464   32382]
Processed Image: IMG_4480.JPG Class: 10
[1378983  112240  309099  191540   33678]
Processed Image: IMG_4488.JPG Class: 10
[738631  56421 174789 104300  13881]
Processed Image: IMG_4490.JPG Class: 10
[556595  40346 139437  67522  12580]
Processed Image: IMG_4490_1.JPG Class: 10
[546196 205204 159844 136118  14758]
Processed Image: IMG_4490_1_2.JPG Class: 10
[346976 259031 126962 110157  14664]
Processed Image: IMG_4490_1_2_3.JPG Class: 10
[542094  39355 135929  65449  12566]
Processed Image: IMG_4490_1_2_3_4.JPG Class: 10
[524667  34219 134164  64320  10360]
Processed Image: IMG_4490_1_2_3_4_5.JPG Class: 10
[541609  45994 136225  72532  10490]
Processed Image: IMG_4498.JPG Class: 10
[745813  70980 166616  92608  16151]
Processed Image: IMG_4498_1.JPG Class: 10
[690901  58596 153231  89067  19253]
Processed Image: IMG_4498_1_2.JPG Class: 10
[940251 102005 202649 150238  24121]
Processed Image: IMG_4498_1_2_

[108294  12269  14909  16980   4859]
Processed Image: IMG_4460_1.JPG Class: 2
[192186  23604  24754  28900  11356]
Processed Image: IMG_4460_1_2.JPG Class: 2
[107732  11196  23647  13898   3178]
Processed Image: IMG_4460_1_2_3.JPG Class: 2
[87033  9464 17265 16237  2697]
Processed Image: IMG_4460_1_2_3_4.JPG Class: 2
[120014   9861  31054  14152   2735]
Processed Image: IMG_4460_1_2_3_4_5.JPG Class: 2
[95872  8459 23369 12187  2619]
Processed Image: IMG_4461.JPG Class: 2
[148341  12295  21334  32566   5487]
Processed Image: IMG_4461_1.JPG Class: 2
[259914  20251  27364  43703  23564]
Processed Image: IMG_4461_1_2.JPG Class: 2
[139950  13555  34264  16044   2575]
Processed Image: IMG_4461_1_2_3.JPG Class: 2
[134664   9680  24435  27384   3337]
Processed Image: IMG_4461_1_2_3_4.JPG Class: 2
[150758  11040  24015  29970   4723]
Processed Image: IMG_4461_1_2_3_4_5.JPG Class: 2
[162092  17116  25660  25364   4110]
Processed Image: IMG_4462.JPG Class: 2
[87531  8325 17547 13985  2308]
Proces

Processed Image: IMG_4433.JPG Class: 3
[421579  43894  84531  73018  16338]
Processed Image: IMG_4434.JPG Class: 3
[265810  23003  52239  41688   7320]
Processed Image: IMG_4435.JPG Class: 3
[441062  47955  64045  65389  22259]
Processed Image: IMG_4439.JPG Class: 3
[488154  33491  87815  96653  13320]
Processed Image: IMG_4443.JPG Class: 3
[384341  41435  60348  58294  16477]
Processed Image: IMG_4444.JPG Class: 3
[146901  18734  33048  31878   3439]
Processed Image: IMG_4445.JPG Class: 3
[511912  46806  95179  97207  15171]
Processed Image: IMG_4446.JPG Class: 3
[545016  47660 104351  96468  14615]
Processed Image: IMG_4447.JPG Class: 3
[503157  99353 106945  96243  25662]
Processed Image: IMG_4449.JPG Class: 3
[260235  28687  52567  48273   9010]
Processed Image: IMG_4451.JPG Class: 3
[246067  24061  41547  40707   8272]
Processed Image: IMG_4451_1.JPG Class: 3
[372624  36257  51991  79533  13452]
Processed Image: IMG_4451_1_2.JPG Class: 3
[228258  23985  40586  32048   9221]
Proces

[7479  684 1147 1058  432]
Processed Image: G0266456.JPG Class: 4
[6558  628 1026  969  341]
Processed Image: G0276458.JPG Class: 4
[19639  2740  3700  1529   364]
Processed Image: G0286462.JPG Class: 4
[19901  1879  3834  2711   715]
Processed Image: G0286463.JPG Class: 4
[22116  2101  4385  3018   780]
Processed Image: G0286464.JPG Class: 4
[16211  1585  2997  2085   666]
Processed Image: G0286465.JPG Class: 4
[20690  2029  3941  3039   739]
Processed Image: G0286466.JPG Class: 4
[18331  1706  3406  2747   702]
Processed Image: G0286467.JPG Class: 4
[20139  1907  3884  2975   732]
Processed Image: G0306494.JPG Class: 4
[13764  1503  1771  1288   706]
Processed Image: G0306495.JPG Class: 4
[14391  1571  1911  1312   744]
Processed Image: G0306496.JPG Class: 4
[17649  1876  2689  1774   897]
Processed Image: G0306498.JPG Class: 4
[17940  1941  2931  1896   834]
Processed Image: G0306501.JPG Class: 4
[21941  2346  3980  2440   973]
Processed Image: G0306502.JPG Class: 4
[15949  1717  26

[23156  2089  4469  2909   992]
Processed Image: G0336544.JPG Class: 5
[17868  1532  3621  2268   703]
Processed Image: G0336546.JPG Class: 5
[16821  1357  3497  2269   626]
Processed Image: G0336547.JPG Class: 5
[18498  1564  3804  2634   716]
Processed Image: G0336548.JPG Class: 5
[19502  1673  4115  2510   742]
Processed Image: G0336549.JPG Class: 5
[18394  1502  3921  2357   736]
Processed Image: G0336550.JPG Class: 5
[18639  1550  4083  2378   686]
Processed Image: G0336551.JPG Class: 5
[19687  1579  4524  2525   593]
Processed Image: IMG_4436.JPG Class: 5
[812534 124813 139726 159443  41364]
Processed Image: IMG_4436_1.JPG Class: 5
[880804  69356 207979 159168  19130]
Processed Image: IMG_4436_1_2.JPG Class: 5
[851903  87477 156270 161307  40369]
Processed Image: IMG_4436_1_2_3.JPG Class: 5
[828235  81406 153953 154824  36038]
Processed Image: IMG_4436_1_2_3_4.JPG Class: 5
[717760 221746 181648 160469  22627]
Processed Image: IMG_4436_1_2_3_4_5.JPG Class: 5
[865131  60143 194358 

# Classification

In [63]:
model = KNeighborsClassifier(n_neighbors=1)
model.fit(train_region,train_classes_region)
predicted_classes = model.predict(test_region)
print("\nKNN Confusion Matrix")
print(confusion_matrix(test_classes_region, predicted_classes))
print("KNN Accuracy Score")
print(accuracy_score(test_classes_region,predicted_classes))

gnb = GaussianNB()
gnb.fit(train_region,train_classes_region)
gnb_predicted_classes = gnb.predict(test_region)
print("\n\nGNB Confusion Matrix")
print(confusion_matrix(test_classes_region, gnb_predicted_classes))
print("GNB Accuracy Score")
print(accuracy_score(test_classes_region,gnb_predicted_classes))


KNN Confusion Matrix
[[ 3  1  0  0  0  0  0  0  0  0  0]
 [ 1 22  7  5  4  0  0  0  0  0  0]
 [ 0  4 24 11  9  0  2  0  0  0  1]
 [ 0  8 13 17  5  2  1  2  0  2  0]
 [ 0  2  7  4  6  2  6  0  0  0  0]
 [ 0  0  7  1  1  4  0  1  0  1  0]
 [ 0  0  1  0  1  0  2  1  1  0  0]
 [ 0  0  0  0  1  0  2  4  0  0  0]
 [ 0  0  0  0  1  0  0  0  5  0  0]
 [ 0  0  0  0  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
KNN Accuracy Score
0.4326923076923077


GNB Confusion Matrix
[[ 3  1  0  0  0  0  0  0  0  0]
 [ 9 22  2  0  1  0  2  3  0  0]
 [ 3 18  6  1  5  0  1 16  1  0]
 [ 1 20  3  2  3  0  1 18  0  2]
 [ 1  5  0  1  2  0  1 14  3  0]
 [ 0  2  0  0  0  0  1 11  0  1]
 [ 0  0  0  0  1  0  1  3  1  0]
 [ 0  0  0  0  0  0  0  7  0  0]
 [ 0  0  0  0  0  0  4  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  3]]
GNB Accuracy Score
0.23076923076923078
