In [12]:
from scipy.fftpack import fft
import skimage.io as io
import os as os 
import numpy as np
import skimage.filters as filt
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import pickle

# Loading Images for FFT

In [6]:
region_features=[]
classes=[]
test_region = []
train_region = []
train_classes_region = []
test_classes_region =[]

rotation_angles=[0,90,180,270]

minimum=0.0
maximum=0.0

for root, dirs, files in os.walk('Data/combined_train_resized'):
    for filename in files:
        cropped_image =  io.imread(root+'/'+filename)
        cropped_image = filt.unsharp_mask(cropped_image, radius=1, amount=4)
        image_class = root.replace("\\","/").split('/')[2]
        for angle in rotation_angles:
            print("Training Image: "+str(filename)+" Class: "+str(image_class)+" Angle: "+str(angle))
            fourier = fft(cropped_image).flatten()
            fourier = np.true_divide(fourier, np.count_nonzero(fourier))
            hist,bins = np.histogram(fourier,bins=5)
            train_region.append(hist)
            train_classes_region.append(int(image_class))
            
for root, dirs, files in os.walk('Data/combined_val_resized'):
    for filename in files:
        cropped_image =  io.imread(root+'/'+filename)
        cropped_image = filt.unsharp_mask(cropped_image, radius=1, amount=4)
        image_class = root.replace("\\","/").split('/')[2]
        for angle in rotation_angles:
            print("Testing Image: "+str(filename)+" Class: "+str(image_class)+" Angle: "+str(angle))
            fourier = fft(cropped_image).flatten()
            fourier = np.true_divide(fourier, np.count_nonzero(fourier))
            hist,bins = np.histogram(fourier,bins=5)
            test_region.append(hist)
            test_classes_region.append(int(image_class))

Training Image: G0166382.png Class: 1 Angle: 0
Training Image: G0166382.png Class: 1 Angle: 90
Training Image: G0166382.png Class: 1 Angle: 180
Training Image: G0166382.png Class: 1 Angle: 270
Training Image: G0166383.png Class: 1 Angle: 0
Training Image: G0166383.png Class: 1 Angle: 90
Training Image: G0166383.png Class: 1 Angle: 180
Training Image: G0166383.png Class: 1 Angle: 270
Training Image: G0166384.png Class: 1 Angle: 0
Training Image: G0166384.png Class: 1 Angle: 90
Training Image: G0166384.png Class: 1 Angle: 180
Training Image: G0166384.png Class: 1 Angle: 270
Training Image: G0296469.png Class: 1 Angle: 0
Training Image: G0296469.png Class: 1 Angle: 90
Training Image: G0296469.png Class: 1 Angle: 180
Training Image: G0296469.png Class: 1 Angle: 270
Training Image: G0296472.png Class: 1 Angle: 0
Training Image: G0296472.png Class: 1 Angle: 90
Training Image: G0296472.png Class: 1 Angle: 180
Training Image: G0296472.png Class: 1 Angle: 270
Training Image: G0296477.png Class:

D:\Anaconda_Installed\lib\site-packages\numpy\lib\function_base.py:786: ComplexWarning: Casting complex values to real discards the imaginary part
  tmp_a_data = tmp_a.astype(float)
D:\Anaconda_Installed\lib\site-packages\numpy\lib\function_base.py:792: ComplexWarning: Casting complex values to real discards the imaginary part
  indices = tmp_a.astype(np.intp)


Training Image: IMG_4488.png Class: 10 Angle: 0
Training Image: IMG_4488.png Class: 10 Angle: 90
Training Image: IMG_4488.png Class: 10 Angle: 180
Training Image: IMG_4488.png Class: 10 Angle: 270
Training Image: IMG_4490_1.png Class: 10 Angle: 0
Training Image: IMG_4490_1.png Class: 10 Angle: 90
Training Image: IMG_4490_1.png Class: 10 Angle: 180
Training Image: IMG_4490_1.png Class: 10 Angle: 270
Training Image: IMG_4490_1_2.png Class: 10 Angle: 0
Training Image: IMG_4490_1_2.png Class: 10 Angle: 90
Training Image: IMG_4490_1_2.png Class: 10 Angle: 180
Training Image: IMG_4490_1_2.png Class: 10 Angle: 270
Training Image: IMG_4490_1_2_3.png Class: 10 Angle: 0
Training Image: IMG_4490_1_2_3.png Class: 10 Angle: 90
Training Image: IMG_4490_1_2_3.png Class: 10 Angle: 180
Training Image: IMG_4490_1_2_3.png Class: 10 Angle: 270
Training Image: IMG_4490_1_2_3_4.png Class: 10 Angle: 0
Training Image: IMG_4490_1_2_3_4.png Class: 10 Angle: 90
Training Image: IMG_4490_1_2_3_4.png Class: 10 Angl

Training Image: G0246436.png Class: 2 Angle: 0
Training Image: G0246436.png Class: 2 Angle: 90
Training Image: G0246436.png Class: 2 Angle: 180
Training Image: G0246436.png Class: 2 Angle: 270
Training Image: G0246437.png Class: 2 Angle: 0
Training Image: G0246437.png Class: 2 Angle: 90
Training Image: G0246437.png Class: 2 Angle: 180
Training Image: G0246437.png Class: 2 Angle: 270
Training Image: G0246438.png Class: 2 Angle: 0
Training Image: G0246438.png Class: 2 Angle: 90
Training Image: G0246438.png Class: 2 Angle: 180
Training Image: G0246438.png Class: 2 Angle: 270
Training Image: G0246439.png Class: 2 Angle: 0
Training Image: G0246439.png Class: 2 Angle: 90
Training Image: G0246439.png Class: 2 Angle: 180
Training Image: G0246439.png Class: 2 Angle: 270
Training Image: G0246440.png Class: 2 Angle: 0
Training Image: G0246440.png Class: 2 Angle: 90
Training Image: G0246440.png Class: 2 Angle: 180
Training Image: G0246440.png Class: 2 Angle: 270
Training Image: G0246442.png Class:

Training Image: IMG_4432_1.png Class: 2 Angle: 270
Training Image: IMG_4434.png Class: 2 Angle: 0
Training Image: IMG_4434.png Class: 2 Angle: 90
Training Image: IMG_4434.png Class: 2 Angle: 180
Training Image: IMG_4434.png Class: 2 Angle: 270
Training Image: IMG_4435.png Class: 2 Angle: 0
Training Image: IMG_4435.png Class: 2 Angle: 90
Training Image: IMG_4435.png Class: 2 Angle: 180
Training Image: IMG_4435.png Class: 2 Angle: 270
Training Image: IMG_4440.png Class: 2 Angle: 0
Training Image: IMG_4440.png Class: 2 Angle: 90
Training Image: IMG_4440.png Class: 2 Angle: 180
Training Image: IMG_4440.png Class: 2 Angle: 270
Training Image: IMG_4453.png Class: 2 Angle: 0
Training Image: IMG_4453.png Class: 2 Angle: 90
Training Image: IMG_4453.png Class: 2 Angle: 180
Training Image: IMG_4453.png Class: 2 Angle: 270
Training Image: IMG_4455.png Class: 2 Angle: 0
Training Image: IMG_4455.png Class: 2 Angle: 90
Training Image: IMG_4455.png Class: 2 Angle: 180
Training Image: IMG_4455.png Clas

Training Image: G0236427.png Class: 3 Angle: 270
Training Image: G0246429.png Class: 3 Angle: 0
Training Image: G0246429.png Class: 3 Angle: 90
Training Image: G0246429.png Class: 3 Angle: 180
Training Image: G0246429.png Class: 3 Angle: 270
Training Image: G0246430.png Class: 3 Angle: 0
Training Image: G0246430.png Class: 3 Angle: 90
Training Image: G0246430.png Class: 3 Angle: 180
Training Image: G0246430.png Class: 3 Angle: 270
Training Image: G0246431.png Class: 3 Angle: 0
Training Image: G0246431.png Class: 3 Angle: 90
Training Image: G0246431.png Class: 3 Angle: 180
Training Image: G0246431.png Class: 3 Angle: 270
Training Image: G0246432.png Class: 3 Angle: 0
Training Image: G0246432.png Class: 3 Angle: 90
Training Image: G0246432.png Class: 3 Angle: 180
Training Image: G0246432.png Class: 3 Angle: 270
Training Image: G0246433.png Class: 3 Angle: 0
Training Image: G0246433.png Class: 3 Angle: 90
Training Image: G0246433.png Class: 3 Angle: 180
Training Image: G0246433.png Class:

Training Image: G0326534.png Class: 3 Angle: 180
Training Image: G0326534.png Class: 3 Angle: 270
Training Image: G0326536.png Class: 3 Angle: 0
Training Image: G0326536.png Class: 3 Angle: 90
Training Image: G0326536.png Class: 3 Angle: 180
Training Image: G0326536.png Class: 3 Angle: 270
Training Image: G0326537.png Class: 3 Angle: 0
Training Image: G0326537.png Class: 3 Angle: 90
Training Image: G0326537.png Class: 3 Angle: 180
Training Image: G0326537.png Class: 3 Angle: 270
Training Image: G0326539.png Class: 3 Angle: 0
Training Image: G0326539.png Class: 3 Angle: 90
Training Image: G0326539.png Class: 3 Angle: 180
Training Image: G0326539.png Class: 3 Angle: 270
Training Image: G0336548.png Class: 3 Angle: 0
Training Image: G0336548.png Class: 3 Angle: 90
Training Image: G0336548.png Class: 3 Angle: 180
Training Image: G0336548.png Class: 3 Angle: 270
Training Image: G0336550.png Class: 3 Angle: 0
Training Image: G0336550.png Class: 3 Angle: 90
Training Image: G0336550.png Class:

Training Image: IMG_4486.png Class: 3 Angle: 90
Training Image: IMG_4486.png Class: 3 Angle: 180
Training Image: IMG_4486.png Class: 3 Angle: 270
Training Image: G0026271.png Class: 4 Angle: 0
Training Image: G0026271.png Class: 4 Angle: 90
Training Image: G0026271.png Class: 4 Angle: 180
Training Image: G0026271.png Class: 4 Angle: 270
Training Image: G0026272.png Class: 4 Angle: 0
Training Image: G0026272.png Class: 4 Angle: 90
Training Image: G0026272.png Class: 4 Angle: 180
Training Image: G0026272.png Class: 4 Angle: 270
Training Image: G0026274.png Class: 4 Angle: 0
Training Image: G0026274.png Class: 4 Angle: 90
Training Image: G0026274.png Class: 4 Angle: 180
Training Image: G0026274.png Class: 4 Angle: 270
Training Image: G0026275.png Class: 4 Angle: 0
Training Image: G0026275.png Class: 4 Angle: 90
Training Image: G0026275.png Class: 4 Angle: 180
Training Image: G0026275.png Class: 4 Angle: 270
Training Image: G0026276.png Class: 4 Angle: 0
Training Image: G0026276.png Class:

Training Image: G0236423.png Class: 4 Angle: 270
Training Image: G0236424.png Class: 4 Angle: 0
Training Image: G0236424.png Class: 4 Angle: 90
Training Image: G0236424.png Class: 4 Angle: 180
Training Image: G0236424.png Class: 4 Angle: 270
Training Image: G0256445.png Class: 4 Angle: 0
Training Image: G0256445.png Class: 4 Angle: 90
Training Image: G0256445.png Class: 4 Angle: 180
Training Image: G0256445.png Class: 4 Angle: 270
Training Image: G0256446.png Class: 4 Angle: 0
Training Image: G0256446.png Class: 4 Angle: 90
Training Image: G0256446.png Class: 4 Angle: 180
Training Image: G0256446.png Class: 4 Angle: 270
Training Image: G0256447.png Class: 4 Angle: 0
Training Image: G0256447.png Class: 4 Angle: 90
Training Image: G0256447.png Class: 4 Angle: 180
Training Image: G0256447.png Class: 4 Angle: 270
Training Image: G0256448.png Class: 4 Angle: 0
Training Image: G0256448.png Class: 4 Angle: 90
Training Image: G0256448.png Class: 4 Angle: 180
Training Image: G0256448.png Class:

Training Image: IMG_4484_1_2.png Class: 4 Angle: 90
Training Image: IMG_4484_1_2.png Class: 4 Angle: 180
Training Image: IMG_4484_1_2.png Class: 4 Angle: 270
Training Image: IMG_4484_1_2_3_4.png Class: 4 Angle: 0
Training Image: IMG_4484_1_2_3_4.png Class: 4 Angle: 90
Training Image: IMG_4484_1_2_3_4.png Class: 4 Angle: 180
Training Image: IMG_4484_1_2_3_4.png Class: 4 Angle: 270
Training Image: IMG_4484_1_2_3_4_5.png Class: 4 Angle: 0
Training Image: IMG_4484_1_2_3_4_5.png Class: 4 Angle: 90
Training Image: IMG_4484_1_2_3_4_5.png Class: 4 Angle: 180
Training Image: IMG_4484_1_2_3_4_5.png Class: 4 Angle: 270
Training Image: IMG_4494.png Class: 4 Angle: 0
Training Image: IMG_4494.png Class: 4 Angle: 90
Training Image: IMG_4494.png Class: 4 Angle: 180
Training Image: IMG_4494.png Class: 4 Angle: 270
Training Image: IMG_4495.png Class: 4 Angle: 0
Training Image: IMG_4495.png Class: 4 Angle: 90
Training Image: IMG_4495.png Class: 4 Angle: 180
Training Image: IMG_4495.png Class: 4 Angle: 27

Training Image: G0336546.png Class: 5 Angle: 90
Training Image: G0336546.png Class: 5 Angle: 180
Training Image: G0336546.png Class: 5 Angle: 270
Training Image: G0336548.png Class: 5 Angle: 0
Training Image: G0336548.png Class: 5 Angle: 90
Training Image: G0336548.png Class: 5 Angle: 180
Training Image: G0336548.png Class: 5 Angle: 270
Training Image: G0336549.png Class: 5 Angle: 0
Training Image: G0336549.png Class: 5 Angle: 90
Training Image: G0336549.png Class: 5 Angle: 180
Training Image: G0336549.png Class: 5 Angle: 270
Training Image: G0336550.png Class: 5 Angle: 0
Training Image: G0336550.png Class: 5 Angle: 90
Training Image: G0336550.png Class: 5 Angle: 180
Training Image: G0336550.png Class: 5 Angle: 270
Training Image: G0336551.png Class: 5 Angle: 0
Training Image: G0336551.png Class: 5 Angle: 90
Training Image: G0336551.png Class: 5 Angle: 180
Training Image: G0336551.png Class: 5 Angle: 270
Training Image: IMG_4436_1_2_3.png Class: 5 Angle: 0
Training Image: IMG_4436_1_2_

Training Image: G0356568.png Class: 6 Angle: 270
Training Image: G0356570.png Class: 6 Angle: 0
Training Image: G0356570.png Class: 6 Angle: 90
Training Image: G0356570.png Class: 6 Angle: 180
Training Image: G0356570.png Class: 6 Angle: 270
Training Image: IMG_4428.png Class: 6 Angle: 0
Training Image: IMG_4428.png Class: 6 Angle: 90
Training Image: IMG_4428.png Class: 6 Angle: 180
Training Image: IMG_4428.png Class: 6 Angle: 270
Training Image: IMG_4459.png Class: 6 Angle: 0
Training Image: IMG_4459.png Class: 6 Angle: 90
Training Image: IMG_4459.png Class: 6 Angle: 180
Training Image: IMG_4459.png Class: 6 Angle: 270
Training Image: IMG_4491.png Class: 6 Angle: 0
Training Image: IMG_4491.png Class: 6 Angle: 90
Training Image: IMG_4491.png Class: 6 Angle: 180
Training Image: IMG_4491.png Class: 6 Angle: 270
Training Image: G0226408.png Class: 7 Angle: 0
Training Image: G0226408.png Class: 7 Angle: 90
Training Image: G0226408.png Class: 7 Angle: 180
Training Image: G0226408.png Class:

Testing Image: G0096343.png Class: 2 Angle: 270
Testing Image: G0096344.png Class: 2 Angle: 0
Testing Image: G0096344.png Class: 2 Angle: 90
Testing Image: G0096344.png Class: 2 Angle: 180
Testing Image: G0096344.png Class: 2 Angle: 270
Testing Image: G0116356.png Class: 2 Angle: 0
Testing Image: G0116356.png Class: 2 Angle: 90
Testing Image: G0116356.png Class: 2 Angle: 180
Testing Image: G0116356.png Class: 2 Angle: 270
Testing Image: G0136364.png Class: 2 Angle: 0
Testing Image: G0136364.png Class: 2 Angle: 90
Testing Image: G0136364.png Class: 2 Angle: 180
Testing Image: G0136364.png Class: 2 Angle: 270
Testing Image: G0166382.png Class: 2 Angle: 0
Testing Image: G0166382.png Class: 2 Angle: 90
Testing Image: G0166382.png Class: 2 Angle: 180
Testing Image: G0166382.png Class: 2 Angle: 270
Testing Image: G0196395.png Class: 2 Angle: 0
Testing Image: G0196395.png Class: 2 Angle: 90
Testing Image: G0196395.png Class: 2 Angle: 180
Testing Image: G0196395.png Class: 2 Angle: 270
Testing

Testing Image: IMG_4473.png Class: 3 Angle: 270
Testing Image: IMG_4473_1_2_3.png Class: 3 Angle: 0
Testing Image: IMG_4473_1_2_3.png Class: 3 Angle: 90
Testing Image: IMG_4473_1_2_3.png Class: 3 Angle: 180
Testing Image: IMG_4473_1_2_3.png Class: 3 Angle: 270
Testing Image: IMG_4475_1_2_3_4_5.png Class: 3 Angle: 0
Testing Image: IMG_4475_1_2_3_4_5.png Class: 3 Angle: 90
Testing Image: IMG_4475_1_2_3_4_5.png Class: 3 Angle: 180
Testing Image: IMG_4475_1_2_3_4_5.png Class: 3 Angle: 270
Testing Image: IMG_4482.png Class: 3 Angle: 0
Testing Image: IMG_4482.png Class: 3 Angle: 90
Testing Image: IMG_4482.png Class: 3 Angle: 180
Testing Image: IMG_4482.png Class: 3 Angle: 270
Testing Image: IMG_4485.png Class: 3 Angle: 0
Testing Image: IMG_4485.png Class: 3 Angle: 90
Testing Image: IMG_4485.png Class: 3 Angle: 180
Testing Image: IMG_4485.png Class: 3 Angle: 270
Testing Image: G0066316.png Class: 4 Angle: 0
Testing Image: G0066316.png Class: 4 Angle: 90
Testing Image: G0066316.png Class: 4 An

# Classification

In [16]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(train_region,train_classes_region)
pickle.dump(model, open('models/KNN_FFT_model.sav', 'wb'))
loaded_model = pickle.load(open('models/KNN_FFT_model.sav', 'rb'))
predicted_classes = loaded_model.predict(test_region)
print("\nKNN Confusion Matrix")
print(confusion_matrix(test_classes_region, predicted_classes))
print("KNN Accuracy Score")
print(accuracy_score(test_classes_region,predicted_classes))


svm_rbf = svm.SVC(kernel='rbf', C=50)
svm_rbf.fit(train_region,train_classes_region)
pickle.dump(svm_rbf, open('models/SVM_FFT_model.sav', 'wb'))
loaded_model = pickle.load(open('models/SVM_FFT_model.sav', 'rb'))
rbf_predicted_classes = loaded_model.predict(test_region)
print("\nSVM Confusion Matrix")
print(confusion_matrix(test_classes_region, rbf_predicted_classes))
print("SVM Accuracy Score")
print(accuracy_score(test_classes_region,rbf_predicted_classes))



gnb = GaussianNB()
gnb.fit(train_region,train_classes_region)
pickle.dump(gnb, open('models/GNB_FFT_model.sav', 'wb'))
loaded_model = pickle.load(open('models/GNB_FFT_model.sav', 'rb'))
gnb_predicted_classes = loaded_model.predict(test_region)
print("\n\nGNB Confusion Matrix")
print(confusion_matrix(test_classes_region, gnb_predicted_classes))
print("GNB Accuracy Score")
print(accuracy_score(test_classes_region,gnb_predicted_classes))


KNN Confusion Matrix
[[28  0  4  0  0  0  0  0  0  0]
 [ 0 48 12 28 12  0  0  4  0  0]
 [ 0 24 72 24 20  8  0  0  0  0]
 [ 0 12 16 24 12  4  0  4  0  4]
 [ 0 16  8 16 16 12  0  0  0  0]
 [ 0  4  8  4  0 12  4  0  0  0]
 [ 0  0  0  4  4  0  0  0  0  0]
 [ 0  0  0  0  8  0  0  4  0  0]
 [ 0  0  0  8  4  0  0  0  4  0]
 [ 0  0  0  0  0  0  0  0  0  8]]
KNN Accuracy Score
0.42857142857142855

SVM Confusion Matrix
[[  0   0  32   0   0   0   0   0   0   0]
 [  0   0 104   0   0   0   0   0   0   0]
 [  0   0 148   0   0   0   0   0   0   0]
 [  0   0  76   0   0   0   0   0   0   0]
 [  0   0  68   0   0   0   0   0   0   0]
 [  0   0  32   0   0   0   0   0   0   0]
 [  0   0   8   0   0   0   0   0   0   0]
 [  0   0  12   0   0   0   0   0   0   0]
 [  0   0  16   0   0   0   0   0   0   0]
 [  0   0   8   0   0   0   0   0   0   0]]
SVM Accuracy Score
0.29365079365079366


GNB Confusion Matrix
[[28  0  0  4  0  0  0  0  0  0]
 [20 40  0 24  0  4  0  4  0 12]
 [ 8 36 12 12 36  4  4  0  