In [130]:
import matplotlib.pyplot as plt
import skimage.util as util
import skimage.io as io
import numpy as np
import os as os 
import skimage as sk
import skimage.color as cl
import skimage.filters as filt 
import scipy.ndimage.filters as fil
import skimage.morphology as morph
import skimage.segmentation as seg
import skimage.measure as measure
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
import skimage.feature as ft
import skimage.exposure as exp
from sklearn.model_selection import train_test_split
from skimage.transform import resize,rotate
import pickle

# LBP and GLCM Helper Functions

In [131]:
def GLCM_feature(Image):
            
    Image =sk.img_as_ubyte(cl.rgb2gray(Image))
    glcm_feature=0
    glcms = ft.greycomatrix(Image,distances=[2,4,8,16,32,48,64,128,256,512],angles=[0.785398,1.5708,3.142],normed=True)
    #glcm_feature_1 = ft.greycoprops(glcms, prop='contrast')
    glcm_feature_2 = ft.greycoprops(glcms, prop='dissimilarity')
    glcm_feature_3 = ft.greycoprops(glcms,prop='correlation')
    
    #glcm_feature_1 = np.mean(glcm_feature_1,axis=1)
    glcm_feature_2 = np.mean(glcm_feature_2,axis=1)
    glcm_feature_3 = np.mean(glcm_feature_3,axis=1)
    
    
    glcm_feature = np.concatenate((glcm_feature_2,glcm_feature_3),axis=None) 
    #print(glcm_feature)
    return glcm_feature

def get_LBP(training_image):
    
    training_image = cl.rgb2gray(training_image)
    Linv_LBP_image=0
    Var_LBP_image=0
    Linv_iterative_histogram=[]
    Var_iterative_histogram=[]
    iterative_histogram=[]
    
    Linv_LBP_image = ft.local_binary_pattern(training_image,P=32,R=3,method='uniform')
    Var_LBP_image = ft.local_binary_pattern(training_image,P=32,R=3,method='var')    
    Linv_iterative_histogram,notneeded = np.histogram(Linv_LBP_image,bins=10,range=(0,9))
    Var_iterative_histogram,notneeded = np.histogram(Var_LBP_image,bins=16,range=(0,7000))
    iterative_histogram = np.concatenate((Linv_iterative_histogram,Var_iterative_histogram),axis=None)
        
    return iterative_histogram

# Feature Extraction on Combined Downgraded Images

In [132]:
GLCM_features=[]
LBPH_features=[]
classes=[]
test_GLCM = []
test_LBPH = []
train_GLCM = []
train_LBPH = []
train_classes_GLCM = []
train_classes_LBPH = []
test_classes_GLCM =[]
test_classes_LBPH =[]

rotation_angles=[0,90,180,270]


for root, dirs, files in os.walk('Data/combined_train_resized'):
    for filename in files:
        cropped_image = sk.img_as_float(io.imread(root+'/'+filename))
        image_class = root.replace("\\","/").split('/')[2]
        for angle in rotation_angles:
            rotated_image = exp.rescale_intensity(rotate(cropped_image,angle))
            print("Training Image: "+str(filename)+" Class: "+str(image_class)+" Angel:"+str(angle))
            train_GLCM.append(GLCM_feature(rotated_image))
            train_LBPH.append(get_LBP(rotated_image))
            train_classes_GLCM.append(int(image_class))
            train_classes_LBPH.append(int(image_class))


for root, dirs, files in os.walk('Data/combined_val_resized/'):
    for filename in files:
        cropped_image =  sk.img_as_float(io.imread(root+'/'+filename))
        image_class = root.replace("\\","/").split('/')[2]
        resized_image = exp.rescale_intensity(cropped_image)
        print("Testing Image: "+str(filename)+" Class: "+str(image_class))
        test_GLCM.append(GLCM_feature(resized_image))
        test_LBPH.append(get_LBP(resized_image))
        test_classes_GLCM.append(int(image_class))
        test_classes_LBPH.append(int(image_class))



Training Image: G0166382.png Class: 1 Angel:0
Training Image: G0166382.png Class: 1 Angel:90


D:\Anaconda_Installed\lib\site-packages\skimage\util\dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8
  .format(dtypeobj_in, dtypeobj_out))
D:\Anaconda_Installed\lib\site-packages\numpy\lib\function_base.py:780: RuntimeWarning: invalid value encountered in greater_equal
  keep = (tmp_a >= first_edge)
D:\Anaconda_Installed\lib\site-packages\numpy\lib\function_base.py:781: RuntimeWarning: invalid value encountered in less_equal
  keep &= (tmp_a <= last_edge)


Training Image: G0166382.png Class: 1 Angel:180
Training Image: G0166382.png Class: 1 Angel:270
Training Image: G0166383.png Class: 1 Angel:0
Training Image: G0166383.png Class: 1 Angel:90
Training Image: G0166383.png Class: 1 Angel:180
Training Image: G0166383.png Class: 1 Angel:270
Training Image: G0166384.png Class: 1 Angel:0
Training Image: G0166384.png Class: 1 Angel:90
Training Image: G0166384.png Class: 1 Angel:180
Training Image: G0166384.png Class: 1 Angel:270
Training Image: G0296469.png Class: 1 Angel:0
Training Image: G0296469.png Class: 1 Angel:90
Training Image: G0296469.png Class: 1 Angel:180
Training Image: G0296469.png Class: 1 Angel:270
Training Image: G0296472.png Class: 1 Angel:0
Training Image: G0296472.png Class: 1 Angel:90
Training Image: G0296472.png Class: 1 Angel:180
Training Image: G0296472.png Class: 1 Angel:270
Training Image: G0296477.png Class: 1 Angel:0
Training Image: G0296477.png Class: 1 Angel:90
Training Image: G0296477.png Class: 1 Angel:180
Trainin

Training Image: G0136365.png Class: 2 Angel:180
Training Image: G0136365.png Class: 2 Angel:270
Training Image: G0136366.png Class: 2 Angel:0
Training Image: G0136366.png Class: 2 Angel:90
Training Image: G0136366.png Class: 2 Angel:180
Training Image: G0136366.png Class: 2 Angel:270
Training Image: G0136367.png Class: 2 Angel:0
Training Image: G0136367.png Class: 2 Angel:90
Training Image: G0136367.png Class: 2 Angel:180
Training Image: G0136367.png Class: 2 Angel:270
Training Image: G0136368.png Class: 2 Angel:0
Training Image: G0136368.png Class: 2 Angel:90
Training Image: G0136368.png Class: 2 Angel:180
Training Image: G0136368.png Class: 2 Angel:270
Training Image: G0136369.png Class: 2 Angel:0
Training Image: G0136369.png Class: 2 Angel:90
Training Image: G0136369.png Class: 2 Angel:180
Training Image: G0136369.png Class: 2 Angel:270
Training Image: G0136370.png Class: 2 Angel:0
Training Image: G0136370.png Class: 2 Angel:90
Training Image: G0136370.png Class: 2 Angel:180
Trainin

Training Image: G0306494.png Class: 2 Angel:90
Training Image: G0306494.png Class: 2 Angel:180
Training Image: G0306494.png Class: 2 Angel:270
Training Image: G0336542.png Class: 2 Angel:0
Training Image: G0336542.png Class: 2 Angel:90
Training Image: G0336542.png Class: 2 Angel:180
Training Image: G0336542.png Class: 2 Angel:270
Training Image: G0336544.png Class: 2 Angel:0
Training Image: G0336544.png Class: 2 Angel:90
Training Image: G0336544.png Class: 2 Angel:180
Training Image: G0336544.png Class: 2 Angel:270
Training Image: G0336546.png Class: 2 Angel:0
Training Image: G0336546.png Class: 2 Angel:90
Training Image: G0336546.png Class: 2 Angel:180
Training Image: G0336546.png Class: 2 Angel:270
Training Image: G0336548.png Class: 2 Angel:0
Training Image: G0336548.png Class: 2 Angel:90
Training Image: G0336548.png Class: 2 Angel:180
Training Image: G0336548.png Class: 2 Angel:270
Training Image: G0336549.png Class: 2 Angel:0
Training Image: G0336549.png Class: 2 Angel:90
Training

Training Image: IMG_4478.png Class: 2 Angel:0
Training Image: IMG_4478.png Class: 2 Angel:90
Training Image: IMG_4478.png Class: 2 Angel:180
Training Image: IMG_4478.png Class: 2 Angel:270
Training Image: IMG_4483.png Class: 2 Angel:0
Training Image: IMG_4483.png Class: 2 Angel:90
Training Image: IMG_4483.png Class: 2 Angel:180
Training Image: IMG_4483.png Class: 2 Angel:270
Training Image: G0146372.png Class: 3 Angel:0
Training Image: G0146372.png Class: 3 Angel:90
Training Image: G0146372.png Class: 3 Angel:180
Training Image: G0146372.png Class: 3 Angel:270
Training Image: G0166380.png Class: 3 Angel:0
Training Image: G0166380.png Class: 3 Angel:90
Training Image: G0166380.png Class: 3 Angel:180
Training Image: G0166380.png Class: 3 Angel:270
Training Image: G0166381.png Class: 3 Angel:0
Training Image: G0166381.png Class: 3 Angel:90
Training Image: G0166381.png Class: 3 Angel:180
Training Image: G0166381.png Class: 3 Angel:270
Training Image: G0166382.png Class: 3 Angel:0
Training 

Training Image: G0286464.png Class: 3 Angel:180
Training Image: G0286464.png Class: 3 Angel:270
Training Image: G0286466.png Class: 3 Angel:0
Training Image: G0286466.png Class: 3 Angel:90
Training Image: G0286466.png Class: 3 Angel:180
Training Image: G0286466.png Class: 3 Angel:270
Training Image: G0296469.png Class: 3 Angel:0
Training Image: G0296469.png Class: 3 Angel:90
Training Image: G0296469.png Class: 3 Angel:180
Training Image: G0296469.png Class: 3 Angel:270
Training Image: G0296472.png Class: 3 Angel:0
Training Image: G0296472.png Class: 3 Angel:90
Training Image: G0296472.png Class: 3 Angel:180
Training Image: G0296472.png Class: 3 Angel:270
Training Image: G0296474.png Class: 3 Angel:0
Training Image: G0296474.png Class: 3 Angel:90
Training Image: G0296474.png Class: 3 Angel:180
Training Image: G0296474.png Class: 3 Angel:270
Training Image: G0296475.png Class: 3 Angel:0
Training Image: G0296475.png Class: 3 Angel:90
Training Image: G0296475.png Class: 3 Angel:180
Trainin

Training Image: IMG_4434.png Class: 3 Angel:0
Training Image: IMG_4434.png Class: 3 Angel:90
Training Image: IMG_4434.png Class: 3 Angel:180
Training Image: IMG_4434.png Class: 3 Angel:270
Training Image: IMG_4435.png Class: 3 Angel:0
Training Image: IMG_4435.png Class: 3 Angel:90
Training Image: IMG_4435.png Class: 3 Angel:180
Training Image: IMG_4435.png Class: 3 Angel:270
Training Image: IMG_4439.png Class: 3 Angel:0
Training Image: IMG_4439.png Class: 3 Angel:90
Training Image: IMG_4439.png Class: 3 Angel:180
Training Image: IMG_4439.png Class: 3 Angel:270
Training Image: IMG_4443.png Class: 3 Angel:0
Training Image: IMG_4443.png Class: 3 Angel:90
Training Image: IMG_4443.png Class: 3 Angel:180
Training Image: IMG_4443.png Class: 3 Angel:270
Training Image: IMG_4445.png Class: 3 Angel:0
Training Image: IMG_4445.png Class: 3 Angel:90
Training Image: IMG_4445.png Class: 3 Angel:180
Training Image: IMG_4445.png Class: 3 Angel:270
Training Image: IMG_4446.png Class: 3 Angel:0
Training 

Training Image: G0036288.png Class: 4 Angel:0
Training Image: G0036288.png Class: 4 Angel:90
Training Image: G0036288.png Class: 4 Angel:180
Training Image: G0036288.png Class: 4 Angel:270
Training Image: G0036289.png Class: 4 Angel:0
Training Image: G0036289.png Class: 4 Angel:90
Training Image: G0036289.png Class: 4 Angel:180
Training Image: G0036289.png Class: 4 Angel:270
Training Image: G0036290.png Class: 4 Angel:0
Training Image: G0036290.png Class: 4 Angel:90
Training Image: G0036290.png Class: 4 Angel:180
Training Image: G0036290.png Class: 4 Angel:270
Training Image: G0036291.png Class: 4 Angel:0
Training Image: G0036291.png Class: 4 Angel:90
Training Image: G0036291.png Class: 4 Angel:180
Training Image: G0036291.png Class: 4 Angel:270
Training Image: G0036292.png Class: 4 Angel:0
Training Image: G0036292.png Class: 4 Angel:90
Training Image: G0036292.png Class: 4 Angel:180
Training Image: G0036292.png Class: 4 Angel:270
Training Image: G0036293.png Class: 4 Angel:0
Training 

Training Image: G0236424.png Class: 4 Angel:270
Training Image: G0256445.png Class: 4 Angel:0
Training Image: G0256445.png Class: 4 Angel:90
Training Image: G0256445.png Class: 4 Angel:180
Training Image: G0256445.png Class: 4 Angel:270
Training Image: G0256446.png Class: 4 Angel:0
Training Image: G0256446.png Class: 4 Angel:90
Training Image: G0256446.png Class: 4 Angel:180
Training Image: G0256446.png Class: 4 Angel:270
Training Image: G0256447.png Class: 4 Angel:0
Training Image: G0256447.png Class: 4 Angel:90
Training Image: G0256447.png Class: 4 Angel:180
Training Image: G0256447.png Class: 4 Angel:270
Training Image: G0256448.png Class: 4 Angel:0
Training Image: G0256448.png Class: 4 Angel:90
Training Image: G0256448.png Class: 4 Angel:180
Training Image: G0256448.png Class: 4 Angel:270
Training Image: G0256449.png Class: 4 Angel:0
Training Image: G0256449.png Class: 4 Angel:90
Training Image: G0256449.png Class: 4 Angel:180
Training Image: G0256449.png Class: 4 Angel:270
Trainin

Training Image: IMG_4456.png Class: 4 Angel:90
Training Image: IMG_4456.png Class: 4 Angel:180
Training Image: IMG_4456.png Class: 4 Angel:270
Training Image: IMG_4456_1_2.png Class: 4 Angel:0
Training Image: IMG_4456_1_2.png Class: 4 Angel:90
Training Image: IMG_4456_1_2.png Class: 4 Angel:180
Training Image: IMG_4456_1_2.png Class: 4 Angel:270
Training Image: IMG_4456_1_2_3.png Class: 4 Angel:0
Training Image: IMG_4456_1_2_3.png Class: 4 Angel:90
Training Image: IMG_4456_1_2_3.png Class: 4 Angel:180
Training Image: IMG_4456_1_2_3.png Class: 4 Angel:270
Training Image: IMG_4456_1_2_3_4.png Class: 4 Angel:0
Training Image: IMG_4456_1_2_3_4.png Class: 4 Angel:90
Training Image: IMG_4456_1_2_3_4.png Class: 4 Angel:180
Training Image: IMG_4456_1_2_3_4.png Class: 4 Angel:270
Training Image: IMG_4456_1_2_3_4_5.png Class: 4 Angel:0
Training Image: IMG_4456_1_2_3_4_5.png Class: 4 Angel:90
Training Image: IMG_4456_1_2_3_4_5.png Class: 4 Angel:180
Training Image: IMG_4456_1_2_3_4_5.png Class: 4

Training Image: G0176386.png Class: 5 Angel:180
Training Image: G0176386.png Class: 5 Angel:270
Training Image: G0176388.png Class: 5 Angel:0
Training Image: G0176388.png Class: 5 Angel:90
Training Image: G0176388.png Class: 5 Angel:180
Training Image: G0176388.png Class: 5 Angel:270
Training Image: G0176389.png Class: 5 Angel:0
Training Image: G0176389.png Class: 5 Angel:90
Training Image: G0176389.png Class: 5 Angel:180
Training Image: G0176389.png Class: 5 Angel:270
Training Image: G0186392.png Class: 5 Angel:0
Training Image: G0186392.png Class: 5 Angel:90
Training Image: G0186392.png Class: 5 Angel:180
Training Image: G0186392.png Class: 5 Angel:270
Training Image: G0236419.png Class: 5 Angel:0
Training Image: G0236419.png Class: 5 Angel:90
Training Image: G0236419.png Class: 5 Angel:180
Training Image: G0236419.png Class: 5 Angel:270
Training Image: G0236420.png Class: 5 Angel:0
Training Image: G0236420.png Class: 5 Angel:90
Training Image: G0236420.png Class: 5 Angel:180
Trainin

Training Image: IMG_4492_1_2_3_4.png Class: 5 Angel:270
Training Image: IMG_4492_1_2_3_4_5.png Class: 5 Angel:0
Training Image: IMG_4492_1_2_3_4_5.png Class: 5 Angel:90
Training Image: IMG_4492_1_2_3_4_5.png Class: 5 Angel:180
Training Image: IMG_4492_1_2_3_4_5.png Class: 5 Angel:270
Training Image: IMG_4493.png Class: 5 Angel:0
Training Image: IMG_4493.png Class: 5 Angel:90
Training Image: IMG_4493.png Class: 5 Angel:180
Training Image: IMG_4493.png Class: 5 Angel:270
Training Image: IMG_4497.png Class: 5 Angel:0
Training Image: IMG_4497.png Class: 5 Angel:90
Training Image: IMG_4497.png Class: 5 Angel:180
Training Image: IMG_4497.png Class: 5 Angel:270
Training Image: IMG_4499.png Class: 5 Angel:0
Training Image: IMG_4499.png Class: 5 Angel:90
Training Image: IMG_4499.png Class: 5 Angel:180
Training Image: IMG_4499.png Class: 5 Angel:270
Training Image: IMG_4500.png Class: 5 Angel:0
Training Image: IMG_4500.png Class: 5 Angel:90
Training Image: IMG_4500.png Class: 5 Angel:180
Trainin

Training Image: G0346564.png Class: 7 Angel:90
Training Image: G0346564.png Class: 7 Angel:180
Training Image: G0346564.png Class: 7 Angel:270
Training Image: G0346565.png Class: 7 Angel:0
Training Image: G0346565.png Class: 7 Angel:90
Training Image: G0346565.png Class: 7 Angel:180
Training Image: G0346565.png Class: 7 Angel:270
Training Image: IMG_4436.png Class: 7 Angel:0
Training Image: IMG_4436.png Class: 7 Angel:90
Training Image: IMG_4436.png Class: 7 Angel:180
Training Image: IMG_4436.png Class: 7 Angel:270
Training Image: IMG_4436_1.png Class: 7 Angel:0
Training Image: IMG_4436_1.png Class: 7 Angel:90
Training Image: IMG_4436_1.png Class: 7 Angel:180
Training Image: IMG_4436_1.png Class: 7 Angel:270
Training Image: IMG_4436_1_2_3.png Class: 7 Angel:0
Training Image: IMG_4436_1_2_3.png Class: 7 Angel:90
Training Image: IMG_4436_1_2_3.png Class: 7 Angel:180
Training Image: IMG_4436_1_2_3.png Class: 7 Angel:270
Training Image: IMG_4436_1_2_3_4.png Class: 7 Angel:0
Training Image:

Testing Image: IMG_4451.png Class: 3
Testing Image: IMG_4451_1.png Class: 3
Testing Image: IMG_4451_1_2_3_4.png Class: 3
Testing Image: IMG_4451_1_2_3_4_5.png Class: 3
Testing Image: IMG_4456_1_2.png Class: 3
Testing Image: IMG_4456_1_2_3_4.png Class: 3
Testing Image: IMG_4458.png Class: 3
Testing Image: IMG_4469.png Class: 3
Testing Image: IMG_4473.png Class: 3
Testing Image: IMG_4473_1_2_3.png Class: 3
Testing Image: IMG_4475_1_2_3_4_5.png Class: 3
Testing Image: IMG_4482.png Class: 3
Testing Image: IMG_4485.png Class: 3
Testing Image: G0066316.png Class: 4
Testing Image: G0086329.png Class: 4
Testing Image: G0086337.png Class: 4
Testing Image: G0216403.png Class: 4
Testing Image: G0236413.png Class: 4
Testing Image: G0236417.png Class: 4
Testing Image: G0266452.png Class: 4
Testing Image: G0266455.png Class: 4
Testing Image: G0276458.png Class: 4
Testing Image: G0286464.png Class: 4
Testing Image: G0306494.png Class: 4
Testing Image: G0326525.png Class: 4
Testing Image: G0326526.png

# Train Test Split

In [133]:
# train_GLCM,test_GLCM,train_classes_GLCM,test_classes_GLCM=train_test_split(GLCM_features, classes, test_size=0.25)
# train_LBPH,test_LBPH,train_classes_LBPH,test_classes_LBPH=train_test_split(LBPH_features, classes, test_size=0.25)

# KNN Classifier for Synthetic and Combined LBP and GLCM

In [134]:
model = KNeighborsClassifier(n_neighbors=10)
model.fit(train_GLCM,train_classes_GLCM)
pickle.dump(model, open('models/KNN_GLCM_model.sav', 'wb'))
loaded_model = pickle.load(open('models/KNN_GLCM_model.sav', 'rb'))
predicted_classes = loaded_model.predict(test_GLCM)
print("\nGLCM Confusion Matrix")
print(confusion_matrix(test_classes_GLCM, predicted_classes))
print("GLCM Accuracy Score")
print(accuracy_score(test_classes_GLCM,predicted_classes))


model = KNeighborsClassifier(n_neighbors=10)
model.fit(train_LBPH,train_classes_LBPH)
pickle.dump(model, open('models/KNN_LBPH_model.sav', 'wb'))
loaded_model = pickle.load(open('models/KNN_LBPH_model.sav', 'rb'))
predicted_classes = loaded_model.predict(test_LBPH)
print("\nLBPH Confusion Matrix")
print(confusion_matrix(test_classes_LBPH, predicted_classes))
print("LPBH Accuracy Score")
print(accuracy_score(test_classes_LBPH,predicted_classes))


GLCM Confusion Matrix
[[ 4  3  1  0  0  0  0  0  0  0]
 [ 0 15  5  6  0  0  0  0  0  0]
 [ 0 11 17  4  3  1  1  0  0  0]
 [ 0  5  2  5  6  0  1  0  0  0]
 [ 0  2  5  2  7  1  0  0  0  0]
 [ 0  0  3  1  0  4  0  0  0  0]
 [ 0  0  0  1  0  0  1  0  0  0]
 [ 0  0  0  0  0  2  0  1  0  0]
 [ 0  0  1  0  1  0  0  0  2  0]
 [ 0  0  0  0  0  0  1  0  0  1]]
GLCM Accuracy Score
0.4523809523809524

LBPH Confusion Matrix
[[ 3  4  1  0  0  0  0  0  0  0]
 [ 0 16  3  3  3  0  1  0  0  0]
 [ 0 11 11  8  2  1  1  3  0  0]
 [ 0  3  4  4  5  0  3  0  0  0]
 [ 0  1  5  7  2  1  1  0  0  0]
 [ 0  2  3  2  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  0  0]
 [ 0  0  1  0  1  0  1  0  0  0]
 [ 0  1  0  2  1  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1]]
LPBH Accuracy Score
0.30158730158730157


# SVM Classifier for Synthetic and Combined LBP and GLCM

In [135]:
svm_rbf = svm.SVC(kernel='rbf', C=10)
svm_rbf.fit(train_GLCM,train_classes_GLCM)
pickle.dump(svm_rbf, open('models/SVM_GLCM_model.sav', 'wb'))
loaded_model = pickle.load(open('models/SVM_GLCM_model.sav', 'rb'))
rbf_predicted_classes = loaded_model.predict(test_GLCM)
print("\nGLCM Confusion Matrix")
print(confusion_matrix(test_classes_GLCM, rbf_predicted_classes))
print("GLCM Accuracy Score")
print(accuracy_score(test_classes_GLCM,rbf_predicted_classes))


svm_rbf = svm.SVC(kernel='rbf', C=10)
svm_rbf.fit(train_LBPH,train_classes_LBPH)
pickle.dump(svm_rbf, open('models/SVM_LBPH_model.sav', 'wb'))
loaded_model = pickle.load(open('models/SVM_LBPH_model.sav', 'rb'))
rbf_predicted_classes = loaded_model.predict(test_LBPH)
print("\nLBPH Confusion Matrix")
print(confusion_matrix(test_classes_LBPH, rbf_predicted_classes))
print("LPBH Accuracy Score")
print(accuracy_score(test_classes_LBPH,rbf_predicted_classes))


GLCM Confusion Matrix
[[ 6  1  1  0  0  0  0  0  0  0  0]
 [ 0 12  8  6  0  0  0  0  0  0  0]
 [ 0  5 23  3  5  0  0  0  0  0  1]
 [ 0  5  6  2  5  0  1  0  0  0  0]
 [ 0  1  4  4  7  1  0  0  0  0  0]
 [ 0  0  3  1  0  4  0  0  0  0  0]
 [ 0  0  0  0  1  0  1  0  0  0  0]
 [ 0  0  1  0  0  0  0  2  0  0  0]
 [ 0  0  0  1  1  0  0  0  2  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
GLCM Accuracy Score
0.47619047619047616

LBPH Confusion Matrix
[[ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0]
 [ 0  0 37  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0]]
LPBH Accuracy Score
0.29365079365079366


# GNB Classifier for Synthetic and Combined LBP and GLCM

In [136]:
gnb = GaussianNB()
gnb.fit(train_GLCM,train_classes_GLCM)
pickle.dump(gnb, open('models/GNB_GLCM_model.sav', 'wb'))
loaded_model = pickle.load(open('models/GNB_GLCM_model.sav', 'rb'))
gnb_predicted_classes = loaded_model.predict(test_GLCM)
print("\nGLCM Confusion Matrix")
print(confusion_matrix(test_classes_GLCM, gnb_predicted_classes))
print("GLCM Accuracy Score")
print(accuracy_score(test_classes_GLCM,gnb_predicted_classes))

gnb = GaussianNB()
gnb.fit(train_LBPH,train_classes_LBPH)
pickle.dump(gnb, open('models/GNB_LBPH_model.sav', 'wb'))
loaded_model = pickle.load(open('models/GNB_LBPH_model.sav', 'rb'))
gnb_predicted_classes = loaded_model.predict(test_LBPH)
print("\nLBPH Confusion Matrix")
print(confusion_matrix(test_classes_LBPH, gnb_predicted_classes))
print("LPBH Accuracy Score")
print(accuracy_score(test_classes_LBPH,gnb_predicted_classes))


GLCM Confusion Matrix
[[ 7  0  0  1  0  0  0  0  0  0]
 [ 6 10  0  2  5  3  0  0  0  0]
 [ 3  6  2  2  5 13  2  4  0  0]
 [ 0  1  1  2  7  7  0  1  0  0]
 [ 0  2  0  4  5  3  0  0  2  1]
 [ 0  0  1  1  0  5  0  0  0  1]
 [ 0  0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  1  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0  2]]
GLCM Accuracy Score
0.30952380952380953

LBPH Confusion Matrix
[[ 7  1  0  0  0  0  0  0  0  0]
 [ 5 11  4  0  0  1  3  0  0  2]
 [ 2  5  1  0  0  5  5 10  1  8]
 [ 0  0  4  0  0  5  1  5  0  4]
 [ 1  3  2  0  0  4  2  2  0  3]
 [ 0  0  0  0  0  3  0  2  0  3]
 [ 0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  1  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0  2]]
LPBH Accuracy Score
0.23809523809523808


# GLCM and LBPH Feature Extaraction on Test Images

In [96]:
# test_GLCM = []
# test_LBPH = []
# train_GLCM = []
# train_LBPH = []
# train_classes_GLCM = []
# train_classes_LBPH = []
# test_classes_GLCM =[]
# test_classes_LBPH =[]
# image_names =[]

# image_resize_width = 500
# image_resize_height = 500
# rotation_angles=[0,90,180,270]

# for root, dirs, files in os.walk('Data/test_images'):
#     for filename in files:
#         if(filename.find("01") is -1 and filename.find("02") is -1 and filename.find("45") is -1 and filename.find("46") is -1):
#             cropped_image =  io.imread(root+'/'+filename)
#             resized_image = resize(cropped_image,(image_resize_height,image_resize_width))
#             print("Testing Image: "+str(filename)+" Given Name: "+str(filename[0:len(filename)-7]) )
#             test_GLCM.append(GLCM_feature(resized_image))
#             test_LBPH.append(get_LBP(resized_image))
#             image_names.append(filename[0:len(filename)-7])
            
# for root, dirs, files in os.walk('Data/Combined_Data'):
#     for filename in files:
#         cropped_image =  io.imread(root+'/'+filename)
#         image_class = root.replace("\\","/").split('/')[2]
#         resized_image = resize(cropped_image,(image_resize_height,image_resize_width))
#         for angle in rotation_angles:
#             print("Processed Image: "+str(filename)+" Class: "+str(image_class)+" Angle: "+str(angle))
#             train_GLCM.append(GLCM_feature(rotate(resized_image,angle)))
#             train_LBPH.append(get_LBP(rotate(resized_image,angle)))
#             train_classes_GLCM.append(image_class)
#             train_classes_LBPH.append(image_class)

In [97]:
# import pandas as pd

# def compute_accuracy(filenames,predicted_count):
#     total_count=0
#     correct_count=0
#     ground_truth = pd.read_csv('Data/real_counts.csv')
    
#     for i in range(0,len(filenames)-1):
#         if(filenames[i] == filenames[i+1]):
#             total_count+=int(predicted_count[i])
#         elif(filenames[i]!=filenames[i+1]):
#             total_count+=int(predicted_count[i])
#             if(total_count == ground_truth.loc[ground_truth['image_name'] == filenames[i] ].iloc[0,1]):
#                 print("Filename: "+str(filenames[i]) + " Count: "+str(total_count))
#                 correct_count+=1
#             total_count=0
#     return correct_count/len(ground_truth)*100
        

# KNN Classifier on Test Images

In [98]:
# print("KNN Classification Test Results")
# model = KNeighborsClassifier(n_neighbors=10)
# model.fit(train_GLCM,train_classes_GLCM)
# predicted_classes = model.predict(test_GLCM)
# print("KNN Accuracy GLCM:"+str(compute_accuracy(image_names,predicted_classes)))


# model = KNeighborsClassifier(n_neighbors=10)
# model.fit(train_LBPH,train_classes_LBPH)
# predicted_classes = model.predict(test_LBPH)
# print("KNN Accuracy LBPH:"+str(compute_accuracy(image_names,predicted_classes)))


# print("\n\nSVM Classification Test Results")
# svm_rbf = svm.SVC(kernel='rbf', C=100)
# svm_rbf.fit(train_GLCM,train_classes_GLCM)
# rbf_predicted_classes = svm_rbf.predict(test_GLCM)
# print("SVM Accuracy GLCM:"+str(compute_accuracy(image_names,rbf_predicted_classes)))


# svm_rbf = svm.SVC(kernel='rbf', C=100)
# svm_rbf.fit(train_LBPH,train_classes_LBPH)
# rbf_predicted_classes = svm_rbf.predict(test_LBPH)
# print("SVM Accuracy LBPH:"+str(compute_accuracy(image_names,rbf_predicted_classes)))

# GLCM and LBPH Feature Extraction on Synthetic Images

In [99]:
# GLCM_features=[]
# LBPH_features=[]
# classes=[]
# test_GLCM = []
# test_LBPH = []
# train_GLCM = []
# train_LBPH = []
# train_classes_GLCM = []
# train_classes_LBPH = []
# test_classes_GLCM =[]
# test_classes_LBPH =[]

# for root, dirs, files in os.walk('Data/synthetic_plants'):
#     for filename in files:
#         if(filename.find("bin") is -1):
#             cropped_image =  io.imread(root+'/'+filename)
#             image_class = filename.split('_')[0]
#             print("Training Image: "+str(filename)+" Class: "+str(image_class))
#             train_GLCM.append(GLCM_feature(cropped_image))
#             train_LBPH.append(get_LBP(cropped_image))
#             train_classes_GLCM.append(image_class)
#             train_classes_LBPH.append(image_class)


# for root, dirs, files in os.walk('Data/Combined_Data'):
#     for filename in files:
#         cropped_image =  io.imread(root+'/'+filename)
#         image_class = root.replace("\\","/").split('/')[2]
#         print("Testing Image: "+str(filename)+" Class: "+str(image_class))
#         test_GLCM.append(GLCM_feature(cropped_image))
#         test_LBPH.append(get_LBP(cropped_image))
#         test_classes_GLCM.append(image_class)
#         test_classes_LBPH.append(image_class)